format = """
$directory\
$git_branch\
$git_state\
$git_status\
$lua\
$nodejs\
$bun\
$golang\
$python\
$fill\
$cmd_duration $jobs\
$line_break\
$character"""

[username]
disabled = true

[hostname]
disabled = true

[lua]
symbol = " "
style="purple"
format = "[$symbol($version )]($style)"

[nodejs]
format = "[$symbol($version )]($style)"
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']

[bun]
format = "[$symbol($version )]($style)"

[golang]
symbol=" "
style="green"
format = "[$symbol($version )]($style)"

[python]
symbol=" "
style = "green"
format = "[$symbol$version (\\($virtualenv\\))]($style) "
detect_files = ["pyproject.toml", "requirements.txt", ".python-version", "setup.py", "Pipfile", "tox.ini"]
detect_extensions = ["py"]

[fill]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "white"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
